name: Flutter Analyze & Test

on:
  push:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'pubspec.yaml'
      - '.github/workflows/flutter-analyze.yml'
  pull_request:
    paths:
      - 'lib/**'
      - 'test/**'
      - 'pubspec.yaml'

jobs:
  flutter-analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.x'
          cache: true

      - name: Disable Flutter Analytics
        run: flutter config --no-analytics

      - name: Pub Get
        run: flutter pub get

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Run Flutter Tests
        run: flutter test --exclude-tags golden
